#cloud-config

# Create a user with sudo access and SSH key
users:
  - name: ${username}
    ssh_authorized_keys:
      - ${ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

# Basic system updates
package_update: true

# Disable password authentication for SSH
ssh_pwauth: false

# Print a message when complete
final_message: "Cloud-init setup completed, system is ready."
